---

- name: setup dns
  template:
    src: etc/resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
    
- name: Update sources.list
  template:
    src: etc/apt/sources.list
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644

- name: Upgrade packages
  apt:
    upgrade: dist
    update_cache: yes

- name: Install packages
  apt:
    name:
      - bash-completion
      - build-essential
      - btrfs-tools
      - cmake
      - curl
      - dnsutils
      - htop
      - iotop
      - isc-dhcp-client
      - iputils-ping
      - kmod
      - linux-firmware
      - locales
      - net-tools
      - netplan.io
      - pciutils
      - python3-dev
      - ssh
      - sudo
      - systemd
      - udev
      - unzip
      - usbutils
      - vim
      - wpasupplicant
      - python-pip
      - python3-pip


- name: Install Nvidia Deps
  apt: 
    name: 
      - device-tree-compiler
      - libasound2
      - libcairo2
      - libdatrie1
      - libevdev2
      - libfontconfig1
      - libgles2
      - libgstreamer-plugins-bad1.0-0
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - libharfbuzz0b
      - libinput10
      - libjpeg-turbo8
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - libunwind8
      - libwayland-cursor0
      - libwayland-egl1
      - libxkbcommon0
      - libxrender1
      
- name: Mark Nvidia Deps
  shell: "apt-mark auto device-tree-compiler libasound2 libcairo2 libdatrie1 libevdev2 libfontconfig1 libgles2 libgstreamer-plugins-bad1.0-0 libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 libharfbuzz0b libinput10 libjpeg-turbo8 libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libpixman-1-0 libpng16-16 libunwind8 libwayland-cursor0 libwayland-egl1 libxkbcommon0 libxrender1"


- name: Generate locales
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Enable services
  shell: systemctl enable {{ item }}
  loop:
    - ssh
    - systemd-networkd
    - systemd-resolved

- name: Create network conf
  template:
    src: etc/netplan/netcfg.yaml
    dest: /etc/netplan/netcfg.yaml
    owner: root
    group: root
    mode: 0644

- name: Create new user
  user:
    name: "{{ new_user.name }}"
    shell: "{{ new_user.shell }}"
    password: "{{ new_user.password | password_hash('sha512') }}"
    create_home: yes
    groups: sudo
    state: present
